//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtual_Mente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION
    {
        public int IDOpcion { get; set; }
        public string DescOpcion { get; set; }
        public int IDPeguntaFK { get; set; }
        public int IDRepuestaCorrectaFK { get; set; }
    
        public virtual REPUESTA_CORRECTA REPUESTA_CORRECTA { get; set; }
        public virtual PREGUNTA PREGUNTA { get; set; }
    }
}
