//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtual_Mente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREGUNTA()
        {
            this.OPCION = new HashSet<OPCION>();
        }
    
        public int IDpregunta { get; set; }
        public string DescPregunta { get; set; }
        public int IDTipoJuegoFK { get; set; }
        public short IDCategoriaFK { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPCION> OPCION { get; set; }
        public virtual TIPO_JUEGO TIPO_JUEGO { get; set; }
    }
}
